---
name: CI
on: [push, pull_request, workflow_dispatch]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js LTS
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - name: Restore cached dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package.json') }}
      - name: Install dependencies
        uses: pnpm/action-setup@v2.1.0
        with:
          run_install: true
      - name: Run Tests
        run: pnpm run ci
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage/coverage-final.json
          token: ${{ secrets.CODECOV_TOKEN }}
